name: Quality Check APAZA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Analyze and summarize issues
        continue-on-error: true
        run: |
          flutter analyze --no-pub --format=json > analyze_output.json

          echo "📊 Resumen del análisis:"
          ERRORS=$(jq '[.diagnostics[] | select(.severity == "ERROR")] | length' analyze_output.json)
          WARNINGS=$(jq '[.diagnostics[] | select(.severity == "WARNING")] | length' analyze_output.json)
          INFOS=$(jq '[.diagnostics[] | select(.severity == "INFO")] | length' analyze_output.json)

          echo "❌ Errores: $ERRORS"
          echo "⚠️ Advertencias: $WARNINGS"
          echo "ℹ️ Información: $INFOS"
